---
title: "Epi 753 Mini Project"
description: |
  Epi 753 Mini Project Results Section
author:
  - name: W3008 Lab Mon/Wed Table 10 
    affiliation: Johns Hopkins
date: "`r Sys.Date()`"
output: distill::distill_article
---


```{r "setup", include = FALSE}
require("knitr")
opts_knit$set(root.dir = "D:/OneDrive - Johns Hopkins/Course/340.753.01 - Epidemiologic Methods 3/Lab/MiniProject/miniproject_stata")
```


```{r}
require(haven)
require(gtsummary)
require(tidyverse)
require(tidymodels)
require(sandwich)
require(lmtest)

setwd("D:/OneDrive - Johns Hopkins/Course/340.753.01 - Epidemiologic Methods 3/Lab/MiniProject/miniproject_stata")

```


```{r}
data <- read_dta("data/project_c_copy-3.dta")
```


# binary anemia


```{r}
data <- data %>% 
    mutate(anemia = ifelse(hb < 13, 1, 0)) %>% 
    mutate(anemia = recode_factor(anemia, "0" = "no", "1" = "yes"))
```


# Table 1


```{r, results = "asis"}
data %>%
    mutate(paids = recode_factor(paids, "0" = "no", "1" = "yes")) %>% 
    mutate(prior = recode_factor(prior, "0" = "no", "1" = "yes")) %>% 
    select(age:anemia) %>% 
    tbl_summary(by = "anemia",
                statistic = list(age ~ "{mean} ({sd})",
                                 bmi ~ "{mean} ({sd})",
                                 paids ~ "{n} ({p}%)",
                                 prior ~ "{n} ({p}%)"),
                digits = list(all_continuous() ~ 1,
                              paids ~ c(0, 1),
                              prior ~ c(0, 1)))
```


# log-binomial regression


```{r, results = "asis"}
glm(cd4lt200 ~ anemia, data = data, family = binomial(link = "log")) %>% 
    tbl_regression(exponentiate = TRUE)
```


```{r}
# glm(cd4lt200 ~ anemia + age + bmi + paids + prior, data = data, family = binomial(link = "log")) %>% 
#     tbl_regression(exponentiate = TRUE)   # fail to converge
```


# Poisson regression


```{r}
model <- coeftest(glm(cd4lt200 ~ anemia + age + bmi + paids + prior, data = data, family = poisson(link = "log")),
         vcov = sandwich)

tidy(model) %>%
  mutate(estimate = exp(estimate)) %>%
  select(term, estimate, `std.error`:`p.value`) %>% 
  kable()
```


```{r}
exp(confint(model))
```

